### ISSUE TITLE
Network device mismatch.

### ISSUE THREAD

**Issue by mcameron** [pellaeon/bsd-cloudinit#11]
Thanks for this tool.  I'm getting em0 in rc.conf, and when I boot in openstack I'm getting vtnet0.  Perhaps this is soemthing unique to my environment?  Causes host to fail to get an ip and consequently fail cloud init.

**Comment by iblis17** [comment]
Hi @mcameron .Actully, we determine the nic at running`installer.sh`. This issue happens, if you create your template on a physical machine.

hmm.. Is there any better way to let it be foolproof ?

**Comment by mcameron** [comment]
I guess you could add echo 'ifconfig_vtnet0="DHCP"' >> /etc/rc.conf to the installer.sh as a default.

However, looking at the  wiki, it looks like this is documented.  I got here from http://docs.openstack.org/image-guide/content/example-freebsd-image.html: so I was using the wrong doc.
