### ISSUE TITLE
loader.conf setting make console not responding to input in single user mode

### ISSUE THREAD

**Issue by pellaeon** [pellaeon/bsd-cloudinit#17]
loader.conf:
`comconsole`

More investigation is needed.

**Comment by iblis17** [comment]
hmm.. do you mean `loader.conf` ?

**Comment by pellaeon** [comment]
Yeah... right xD

**Comment by iblis17** [comment]
FYI: https://github.com/pellaeon/bsd-cloudinit-installer/blob/master/installer.sh#L107-L110

You can run `env BSDINIT_DEBUG=1 installer.sh` to build testing image.

**Comment by iblis17** [comment]
Fixed via  pellaeon/bsd-cloudinit-installer@18b452f6
