### ISSUE TITLE
user-data support

### ISSUE THREAD

**Issue by vtolstov** [pellaeon/bsd-cloudinit#5]
Do you have any plans to support user-data? I need to set root password and install ssh keys for root.

**Comment by charliedrage** [comment]
anyone know if this has been implemented? i saw that digitalocean has added freebsd using bsd-cloudinit, but *how* did they do it?

**Comment by iblis17** [comment]
Hi @charliedrage. AFAIK, our upstream, cloudbase-init, already implement some plugin for user data.
We only need to add some `osutils` function to leverage it.

**Comment by martymac** [comment]
Here is a very simple implementation of user data support :
https://github.com/pellaeon/bsd-cloudinit/pull/26

It does not examine data header and is currently restricted to executing scripts.
