### ISSUE TITLE
Showing root password generated randomly at console

### ISSUE THREAD

**Issue by iblis17** [pellaeon/bsd-cloudinit#9]

**Comment by sc68cal** [comment]
I don't think this is a good idea. There are already APIs in AWS and [OpenStack that return the generated password in the response] (http://developer.openstack.org/api-ref-compute-v2.html). For security reasons, you cannot retrieve the password in subsequent requests, so why would we display it on the console?

```
If you do not specify a password, a randomly generated password is assigned and returned in the response object. This password is guaranteed to meet the security requirements set by the compute provider. For security reasons, the password is not returned in subsequent GET calls. 
```

**Comment by iblis17** [comment]
Thanks for your suggestion. Sounds great. 
When I try to deal with `adminPass` metadata, I encounter some problem.

The `adminPass` is generated by `nova`, and `nova` will inject it by itself.( ref: [inject_password option](https://github.com/openstack/nova/blob/90f843cdc47b494cd568507820d45868765697b1/nova/virt/libvirt/driver.py#L129) )
And how do `nova` inject admin password? It just modified `/etc/shadow` and `/etc/password`.
Certainly, this [inject function](https://github.com/openstack/nova/blob/90f843cdc47b494cd568507820d45868765697b1/nova/virt/disk/api.py#L593) is'nt suitable for FreeBSD unless we patch `nova`.

So I think the alternative policy is: 
Let our script post password to `nova` api, and user can get the password with `nova` client. The `adminPass` will not work.

FYI, this command can get the password if we post password to api(http://169.254.169.254/openstack/latest/password):
```
$ nova get-password <VM-id> <ssh private key>
```
